default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 1000
  strict: false
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock


development:
  <<: *default
  database: jruby_splice_development

test:
  <<: *default
  database: jruby_splice_test

production:
  <<: *default
  database: jruby_splice_production
